[package]
name = "halo2_solidity_verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1", default_features = false }
serde = { version = "1.0.126", features = ["derive"] }
log = { version = "0.4.17", default_features = false }


[dev-dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_04_20" }
snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier", tag = "v2023_04_20"}
ethers = { version = "2.0.7", default_features = false, features = ["ethers-solc"] }
rand = { version = "0.8", default_features = false }
tokio = { version = "1.26.0",  default_features = false, features = ["macros", "rt"] }
